### ISSUE TITLE
Missing git tags for newer releases

### ISSUE THREAD

**Issue by felixonmars** [ioquatix/bake#10]
It would be nice to keep rubygems releases and git tags in sync :)

**Comment by ioquatix** [comment]
There was a bug in one of my tools for a while and I missed it so a bunch of tags were missing across different projects. It's since fixed but it only updates all the tags on release of a new version so it will take time for everything to get back into sync.

Anyway, thanks for mentioning it, I have pushed as many local missing tags as I have :)
